### ISSUE TITLE
minimum samplerate

### ISSUE THREAD

**Issue by mipac** [lordmulder/DynamicAudioNormalizer#17]
Hi,
The minimum samplerate is hardfixed to 11025Hz in API code.
I've test with 8000Hz for my current project and everything seems OK
Is there a reason behind this limitation or it could be changed to a min of 8000Hz?

regards,
Michel

**Comment by lordmulder** [comment]
Not really. The sample rate is used (only) to compute the number of samples per "frame", because frame size is specified by milliseconds. So, we have to ensure that sample rate is a "sane" value.

However the choice of 11,025 Hz as the minimum was kind of arbitrary. It is lowered to 8,000 Hz now.

Regards.
