### ISSUE TITLE
Output doesn’t show much difference

### ISSUE THREAD

**Issue by AVer-V003280** [lordmulder/DynamicAudioNormalizer#30]
First of all, thank you for providing the repository. I’m new to this. I used DynamicAudioNormalizer.2017-04-14.Windows-DLL package. I ran the command: 
DynamicAudioNormalizerCLI.exe -i "example4_no_noise_16k.wav" -o "out_normalized.wav" in the Windows command prompt, but the output doesn’t show much difference. 

![image](https://github.com/user-attachments/assets/12613ec3-f665-4286-b29c-eada22491479)

Could you please let me know if I made a mistake somewhere?

Thanks in advance!
tim chen

**Comment by lordmulder** [comment]
DynamicAudioNormalizer is **not** supposed to "show much difference" 😏 

It _smoothes_ the amplification factors over time to get consistent result (hopefully) instead of annoying "volume pumping".

Anyhow, there are many parameters you can tweak &ndash; most important the **`-g`** parameter!

So, what exactly are your parameters? All on default? If so, have you tried a somewhat _smaller_ `-g` value (default is 31), which will smooth over a _shorter_ time window and therefore produce a _faster_ adaption (alteration) of the amplification factors?

Also, you may want to use option `-l` to produce a log file and inspect it with the `DynamicAudioNormalizerGUI.exe` application.

**See also:**
[Why does DynAudNorm not seem to change my audio at all?](https://github.com/lordmulder/DynamicAudioNormalizer?tab=readme-ov-file#q-why-does-dynaudnorm-not-seem-to-change-my-audio-at-all---)

Regards.
